// <auto-generated />
using System;
using DATN_WebDT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DATN_WebDT.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260210074914_db")]
    partial class db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DATN_WebDT.Models.AnhSanPham", b =>
                {
                    b.Property<int>("IdAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnh"));

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdModelSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("SanPhamChiTietIdModelSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("SanPhamIdSanPham")
                        .HasColumnType("int");

                    b.HasKey("IdAnh");

                    b.HasIndex("IdModelSanPham");

                    b.HasIndex("SanPhamChiTietIdModelSanPham");

                    b.HasIndex("SanPhamIdSanPham");

                    b.ToTable("AnhSanPhams");
                });

            modelBuilder.Entity("DATN_WebDT.Models.BaoHanh", b =>
                {
                    b.Property<int>("IdBaoHanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaoHanh"));

                    b.Property<string>("ChiPhiPhatSinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdImei")
                        .HasColumnType("int");

                    b.Property<int>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("MoTaLoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XuLyPhatSinh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBaoHanh");

                    b.HasIndex("IdImei");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("BaoHanhs");
                });

            modelBuilder.Entity("DATN_WebDT.Models.CameraSau", b =>
                {
                    b.Property<int>("IdCameraSau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCameraSau"));

                    b.Property<string>("DoPhanGiaiCameraSau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaCameraSau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuayVideoCameraSau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoLuongOngKinh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCameraSau");

                    b.ToTable("CameraSaus");
                });

            modelBuilder.Entity("DATN_WebDT.Models.CameraTruoc", b =>
                {
                    b.Property<int>("IdCameraTruoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCameraTruoc"));

                    b.Property<string>("DoPhanGiaiCameraTruoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuayVideoCameraTruoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhNangCameraTruoc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCameraTruoc");

                    b.ToTable("CameraTruocs");
                });

            modelBuilder.Entity("DATN_WebDT.Models.DiaChi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChiChiTiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("PhuongXa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuanHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoaiNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThanhPho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("diachis");
                });

            modelBuilder.Entity("DATN_WebDT.Models.DonHang", b =>
                {
                    b.Property<int>("IdDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDonHang"));

                    b.Property<string>("DiaChiGiaoHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HoaDonIdHoaDon")
                        .HasColumnType("int");

                    b.Property<int?>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NhanVienIdNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiDonHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiHoaDon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDonHang");

                    b.HasIndex("HoaDonIdHoaDon");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("NhanVienIdNhanVien");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("DATN_WebDT.Models.DonHangChiTiet", b =>
                {
                    b.Property<int>("IdDonHangChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDonHangChiTiet"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdDonHang")
                        .HasColumnType("int");

                    b.Property<int>("IdKhuyenMai")
                        .HasColumnType("int");

                    b.Property<int>("IdModelSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("SanPhamChiTietIdModelSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdDonHangChiTiet");

                    b.HasIndex("IdDonHang");

                    b.HasIndex("IdKhuyenMai");

                    b.HasIndex("IdModelSanPham");

                    b.HasIndex("SanPhamChiTietIdModelSanPham");

                    b.ToTable("DonHangChiTiets");
                });

            modelBuilder.Entity("DATN_WebDT.Models.GioHang", b =>
                {
                    b.Property<int>("IdGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGioHang"));

                    b.Property<int>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGioHang");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("DATN_WebDT.Models.GioHangChiTiet", b =>
                {
                    b.Property<int>("IdGioHangChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGioHangChiTiet"));

                    b.Property<int>("IdGioHang")
                        .HasColumnType("int");

                    b.Property<int>("IdModelSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdGioHangChiTiet");

                    b.HasIndex("IdGioHang");

                    b.HasIndex("IdModelSanPham");

                    b.ToTable("GioHangChiTiets");
                });

            modelBuilder.Entity("DATN_WebDT.Models.HoaDon", b =>
                {
                    b.Property<int>("IdHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHoaDon"));

                    b.Property<int?>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("IdKhuyenMai")
                        .HasColumnType("int");

                    b.Property<int?>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLapHoaDon")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiHoaDon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHoaDon");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdKhuyenMai");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("DATN_WebDT.Models.HoaDonChiTiet", b =>
                {
                    b.Property<int>("IdHoaDonChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHoaDonChiTiet"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdHoaDon")
                        .HasColumnType("int");

                    b.Property<int?>("IdImei")
                        .HasColumnType("int");

                    b.Property<int?>("IdModelSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdHoaDonChiTiet");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdImei");

                    b.HasIndex("IdModelSanPham");

                    b.ToTable("HoaDonChiTiets");
                });

            modelBuilder.Entity("DATN_WebDT.Models.Imei", b =>
                {
                    b.Property<int>("IdImei")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImei"));

                    b.Property<int?>("BaoHanhIdBaoHanh")
                        .HasColumnType("int");

                    b.Property<int>("IdModelSanPham")
                        .HasColumnType("int");

                    b.Property<string>("MaImei")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SanPhamChiTietIdModelSanPham")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdImei");

                    b.HasIndex("BaoHanhIdBaoHanh");

                    b.HasIndex("IdModelSanPham");

                    b.HasIndex("MaImei")
                        .IsUnique();

                    b.HasIndex("SanPhamChiTietIdModelSanPham");

                    b.ToTable("Imeis");
                });

            modelBuilder.Entity("DATN_WebDT.Models.KhachHang", b =>
                {
                    b.Property<int>("IdKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKhachHang"));

                    b.Property<string>("DefaultImageKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoaiKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKhachHang");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("DATN_WebDT.Models.Kho", b =>
                {
                    b.Property<int>("IdKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKho"));

                    b.Property<string>("DiaChiKho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoaiKho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKho");

                    b.ToTable("Khos");
                });

            modelBuilder.Entity("DATN_WebDT.Models.KhuyenMai", b =>
                {
                    b.Property<int>("IdKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKhuyenMai"));

                    b.Property<bool?>("ApDungVoiDonHang")
                        .HasColumnType("bit");

                    b.Property<string>("MaKM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaKhuyenMai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MucGiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKhuyenMai");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("DATN_WebDT.Models.ManHinh", b =>
                {
                    b.Property<int>("IdManHinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdManHinh"));

                    b.Property<string>("CongNgheManHinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoPhanGiai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KichThuocManHinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaManHinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhNangManHinh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdManHinh");

                    b.ToTable("ManHinhs");
                });

            modelBuilder.Entity("DATN_WebDT.Models.NhanVien", b =>
                {
                    b.Property<int>("IdNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNhanVien"));

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNhanVien");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("DATN_WebDT.Models.Pin", b =>
                {
                    b.Property<int>("IdPin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPin"));

                    b.Property<string>("CongNgheSac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DungLuongPin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiPin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaPin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPin");

                    b.ToTable("Pins");
                });

            modelBuilder.Entity("DATN_WebDT.Models.RAM", b =>
                {
                    b.Property<int>("IdRAM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRAM"));

                    b.Property<string>("DungLuongRAM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaRAM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRAM");

                    b.ToTable("RAMs");
                });

            modelBuilder.Entity("DATN_WebDT.Models.ROM", b =>
                {
                    b.Property<int>("IdROM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdROM"));

                    b.Property<string>("DungLuongROM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaROM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdROM");

                    b.ToTable("ROMs");
                });

            modelBuilder.Entity("DATN_WebDT.Models.SanPham", b =>
                {
                    b.Property<int>("IdSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSanPham"));

                    b.Property<decimal>("GiaGoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GiaGocVAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GiaYeuThich")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdThuongHieu")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiSP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSanPham");

                    b.HasIndex("IdThuongHieu");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("DATN_WebDT.Models.SanPhamChiTiet", b =>
                {
                    b.Property<int>("IdModelSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModelSanPham"));

                    b.Property<string>("GiaModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCameraSau")
                        .HasColumnType("int");

                    b.Property<int?>("IdCameraTruoc")
                        .HasColumnType("int");

                    b.Property<int?>("IdManHinh")
                        .HasColumnType("int");

                    b.Property<int?>("IdPin")
                        .HasColumnType("int");

                    b.Property<int?>("IdRAM")
                        .HasColumnType("int");

                    b.Property<int?>("IdROM")
                        .HasColumnType("int");

                    b.Property<int>("IdSanPham")
                        .HasColumnType("int");

                    b.Property<string>("MauSac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdModelSanPham");

                    b.HasIndex("IdCameraSau");

                    b.HasIndex("IdCameraTruoc");

                    b.HasIndex("IdManHinh");

                    b.HasIndex("IdPin");

                    b.HasIndex("IdRAM");

                    b.HasIndex("IdROM");

                    b.HasIndex("IdSanPham");

                    b.ToTable("SanPhamCTs");
                });

            modelBuilder.Entity("DATN_WebDT.Models.TaiKhoan", b =>
                {
                    b.Property<int>("IdTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTaiKhoan"));

                    b.Property<int?>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTaiKhoan");

                    b.HasIndex("IdKhachHang")
                        .IsUnique()
                        .HasFilter("[IdKhachHang] IS NOT NULL");

                    b.HasIndex("IdNhanVien")
                        .IsUnique()
                        .HasFilter("[IdNhanVien] IS NOT NULL");

                    b.ToTable("taiKhoans");
                });

            modelBuilder.Entity("DATN_WebDT.Models.ThanhToan", b =>
                {
                    b.Property<int>("IdThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThanhToan"));

                    b.Property<int>("HinhThuc")
                        .HasColumnType("int");

                    b.Property<int>("IdHoaDon")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdThanhToan");

                    b.HasIndex("IdHoaDon");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("DATN_WebDT.Models.ThuongHieu", b =>
                {
                    b.Property<int>("IdThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThuongHieu"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThaiThuongHieu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdThuongHieu");

                    b.ToTable("ThuongHieus");
                });

            modelBuilder.Entity("DATN_WebDT.Models.TonKho", b =>
                {
                    b.Property<int?>("IdTonKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdTonKho"));

                    b.Property<int?>("IdKho")
                        .HasColumnType("int");

                    b.Property<int?>("IdModelSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdTonKho");

                    b.HasIndex("IdKho");

                    b.HasIndex("IdModelSanPham");

                    b.ToTable("TonKhos");
                });

            modelBuilder.Entity("DATN_WebDT.Models.AnhSanPham", b =>
                {
                    b.HasOne("DATN_WebDT.Models.SanPhamChiTiet", "SanPhamCT")
                        .WithMany()
                        .HasForeignKey("IdModelSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_WebDT.Models.SanPhamChiTiet", null)
                        .WithMany("AnhSanPhams")
                        .HasForeignKey("SanPhamChiTietIdModelSanPham");

                    b.HasOne("DATN_WebDT.Models.SanPham", null)
                        .WithMany("AnhSanPhams")
                        .HasForeignKey("SanPhamIdSanPham");

                    b.Navigation("SanPhamCT");
                });

            modelBuilder.Entity("DATN_WebDT.Models.BaoHanh", b =>
                {
                    b.HasOne("DATN_WebDT.Models.Imei", "Imei")
                        .WithMany()
                        .HasForeignKey("IdImei")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DATN_WebDT.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Imei");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DATN_WebDT.Models.DiaChi", b =>
                {
                    b.HasOne("DATN_WebDT.Models.KhachHang", "KhachHang")
                        .WithMany("Diachi")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DATN_WebDT.Models.DonHang", b =>
                {
                    b.HasOne("DATN_WebDT.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("HoaDonIdHoaDon");

                    b.HasOne("DATN_WebDT.Models.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DATN_WebDT.Models.NhanVien", "NhanVien")
                        .WithMany("DonHangs")
                        .HasForeignKey("NhanVienIdNhanVien");

                    b.Navigation("HoaDon");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DATN_WebDT.Models.DonHangChiTiet", b =>
                {
                    b.HasOne("DATN_WebDT.Models.DonHang", "DonHang")
                        .WithMany("DonHangChiTiets")
                        .HasForeignKey("IdDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_WebDT.Models.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("IdKhuyenMai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DATN_WebDT.Models.SanPhamChiTiet", "SanPhamCT")
                        .WithMany()
                        .HasForeignKey("IdModelSanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DATN_WebDT.Models.SanPhamChiTiet", null)
                        .WithMany("DonHangChiTiets")
                        .HasForeignKey("SanPhamChiTietIdModelSanPham");

                    b.Navigation("DonHang");

                    b.Navigation("KhuyenMai");

                    b.Navigation("SanPhamCT");
                });

            modelBuilder.Entity("DATN_WebDT.Models.GioHang", b =>
                {
                    b.HasOne("DATN_WebDT.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DATN_WebDT.Models.GioHangChiTiet", b =>
                {
                    b.HasOne("DATN_WebDT.Models.GioHang", "GioHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_WebDT.Models.SanPhamChiTiet", "SanPhamCT")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdModelSanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("SanPhamCT");
                });

            modelBuilder.Entity("DATN_WebDT.Models.HoaDon", b =>
                {
                    b.HasOne("DATN_WebDT.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DATN_WebDT.Models.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("IdKhuyenMai")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DATN_WebDT.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DATN_WebDT.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("DATN_WebDT.Models.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_WebDT.Models.Imei", "Imei")
                        .WithMany()
                        .HasForeignKey("IdImei")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DATN_WebDT.Models.SanPhamChiTiet", "SanPhamCT")
                        .WithMany()
                        .HasForeignKey("IdModelSanPham")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HoaDon");

                    b.Navigation("Imei");

                    b.Navigation("SanPhamCT");
                });

            modelBuilder.Entity("DATN_WebDT.Models.Imei", b =>
                {
                    b.HasOne("DATN_WebDT.Models.BaoHanh", "BaoHanh")
                        .WithMany()
                        .HasForeignKey("BaoHanhIdBaoHanh");

                    b.HasOne("DATN_WebDT.Models.SanPhamChiTiet", "SanPhamCT")
                        .WithMany()
                        .HasForeignKey("IdModelSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_WebDT.Models.SanPhamChiTiet", null)
                        .WithMany("Imeis")
                        .HasForeignKey("SanPhamChiTietIdModelSanPham");

                    b.Navigation("BaoHanh");

                    b.Navigation("SanPhamCT");
                });

            modelBuilder.Entity("DATN_WebDT.Models.SanPham", b =>
                {
                    b.HasOne("DATN_WebDT.Models.ThuongHieu", "ThuongHieu")
                        .WithMany()
                        .HasForeignKey("IdThuongHieu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("DATN_WebDT.Models.SanPhamChiTiet", b =>
                {
                    b.HasOne("DATN_WebDT.Models.CameraSau", "CameraSau")
                        .WithMany()
                        .HasForeignKey("IdCameraSau")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DATN_WebDT.Models.CameraTruoc", "CameraTruoc")
                        .WithMany()
                        .HasForeignKey("IdCameraTruoc")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DATN_WebDT.Models.ManHinh", "ManHinh")
                        .WithMany()
                        .HasForeignKey("IdManHinh")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DATN_WebDT.Models.Pin", "Pin")
                        .WithMany()
                        .HasForeignKey("IdPin")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DATN_WebDT.Models.RAM", "RAM")
                        .WithMany()
                        .HasForeignKey("IdRAM")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DATN_WebDT.Models.ROM", "ROM")
                        .WithMany()
                        .HasForeignKey("IdROM")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DATN_WebDT.Models.SanPham", "SanPham")
                        .WithMany("ModelSanPhams")
                        .HasForeignKey("IdSanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CameraSau");

                    b.Navigation("CameraTruoc");

                    b.Navigation("ManHinh");

                    b.Navigation("Pin");

                    b.Navigation("RAM");

                    b.Navigation("ROM");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DATN_WebDT.Models.TaiKhoan", b =>
                {
                    b.HasOne("DATN_WebDT.Models.KhachHang", "KhachHang")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("DATN_WebDT.Models.TaiKhoan", "IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DATN_WebDT.Models.NhanVien", "NhanVien")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("DATN_WebDT.Models.TaiKhoan", "IdNhanVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DATN_WebDT.Models.ThanhToan", b =>
                {
                    b.HasOne("DATN_WebDT.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("DATN_WebDT.Models.TonKho", b =>
                {
                    b.HasOne("DATN_WebDT.Models.Kho", "Kho")
                        .WithMany("TonKhos")
                        .HasForeignKey("IdKho")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DATN_WebDT.Models.SanPhamChiTiet", "SanPhamCT")
                        .WithMany()
                        .HasForeignKey("IdModelSanPham")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Kho");

                    b.Navigation("SanPhamCT");
                });

            modelBuilder.Entity("DATN_WebDT.Models.DonHang", b =>
                {
                    b.Navigation("DonHangChiTiets");
                });

            modelBuilder.Entity("DATN_WebDT.Models.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("DATN_WebDT.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("DATN_WebDT.Models.KhachHang", b =>
                {
                    b.Navigation("Diachi");

                    b.Navigation("DonHangs");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DATN_WebDT.Models.Kho", b =>
                {
                    b.Navigation("TonKhos");
                });

            modelBuilder.Entity("DATN_WebDT.Models.NhanVien", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DATN_WebDT.Models.SanPham", b =>
                {
                    b.Navigation("AnhSanPhams");

                    b.Navigation("ModelSanPhams");
                });

            modelBuilder.Entity("DATN_WebDT.Models.SanPhamChiTiet", b =>
                {
                    b.Navigation("AnhSanPhams");

                    b.Navigation("DonHangChiTiets");

                    b.Navigation("GioHangChiTiets");

                    b.Navigation("Imeis");
                });
#pragma warning restore 612, 618
        }
    }
}
