// <auto-generated />
using System;
using DATN_WebDT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DATN_WebDT.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DATN_WebDT.Models.AnhSanPham", b =>
                {
                    b.Property<int>("IdAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnh"));

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdModelSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("SanPhamChiTietIdSanPhamChiTiet")
                        .HasColumnType("int");

                    b.Property<int?>("SanPhamIdSanPham")
                        .HasColumnType("int");

                    b.HasKey("IdAnh");

                    b.HasIndex("IdModelSanPham");

                    b.HasIndex("SanPhamChiTietIdSanPhamChiTiet");

                    b.HasIndex("SanPhamIdSanPham");

                    b.ToTable("AnhSanPhams");
                });

            modelBuilder.Entity("DATN_WebDT.Models.ChiTietCongThuc", b =>
                {
                    b.Property<int>("IdSanPhamChiTiet")
                        .HasColumnType("int");

                    b.Property<int>("IdNguyenLieu")
                        .HasColumnType("int");

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoLuongCanDung")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("IdSanPhamChiTiet", "IdNguyenLieu");

                    b.HasIndex("IdNguyenLieu");

                    b.ToTable("ChiTietCongThucs");
                });

            modelBuilder.Entity("DATN_WebDT.Models.DiaChi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChiChiTiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("PhuongXa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuanHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoaiNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThanhPho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("diachis");
                });

            modelBuilder.Entity("DATN_WebDT.Models.DonHang", b =>
                {
                    b.Property<int>("IdDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDonHang"));

                    b.Property<string>("DiaChiGiaoHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HoaDonIdHoaDon")
                        .HasColumnType("int");

                    b.Property<int?>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NhanVienIdNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiDonHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiHoaDon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDonHang");

                    b.HasIndex("HoaDonIdHoaDon");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("NhanVienIdNhanVien");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("DATN_WebDT.Models.DonHangChiTiet", b =>
                {
                    b.Property<int>("IdDonHangChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDonHangChiTiet"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdDonHang")
                        .HasColumnType("int");

                    b.Property<int>("IdKhuyenMai")
                        .HasColumnType("int");

                    b.Property<int>("IdModelSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("SanPhamChiTietIdSanPhamChiTiet")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdDonHangChiTiet");

                    b.HasIndex("IdDonHang");

                    b.HasIndex("IdKhuyenMai");

                    b.HasIndex("IdModelSanPham");

                    b.HasIndex("SanPhamChiTietIdSanPhamChiTiet");

                    b.ToTable("DonHangChiTiets");
                });

            modelBuilder.Entity("DATN_WebDT.Models.GioHang", b =>
                {
                    b.Property<int>("IdGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGioHang"));

                    b.Property<int>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGioHang");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("DATN_WebDT.Models.GioHangChiTiet", b =>
                {
                    b.Property<int>("IdGioHangChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGioHangChiTiet"));

                    b.Property<int>("IdGioHang")
                        .HasColumnType("int");

                    b.Property<int>("IdModelSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdGioHangChiTiet");

                    b.HasIndex("IdGioHang");

                    b.HasIndex("IdModelSanPham");

                    b.ToTable("GioHangChiTiets");
                });

            modelBuilder.Entity("DATN_WebDT.Models.HoaDon", b =>
                {
                    b.Property<int>("IdHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHoaDon"));

                    b.Property<int?>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("IdKhuyenMai")
                        .HasColumnType("int");

                    b.Property<int?>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLapHoaDon")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiHoaDon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHoaDon");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdKhuyenMai");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("DATN_WebDT.Models.HoaDonChiTiet", b =>
                {
                    b.Property<int>("IdHoaDonChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHoaDonChiTiet"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdHoaDon")
                        .HasColumnType("int");

                    b.Property<int?>("IdModelSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdHoaDonChiTiet");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdModelSanPham");

                    b.ToTable("HoaDonChiTiets");
                });

            modelBuilder.Entity("DATN_WebDT.Models.KhachHang", b =>
                {
                    b.Property<int>("IdKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKhachHang"));

                    b.Property<string>("DefaultImageKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoaiKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKhachHang");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("DATN_WebDT.Models.Kho", b =>
                {
                    b.Property<int>("IdKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKho"));

                    b.Property<string>("DiaChiKho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoaiKho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKho");

                    b.ToTable("Khos");
                });

            modelBuilder.Entity("DATN_WebDT.Models.KhuyenMai", b =>
                {
                    b.Property<int>("IdKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKhuyenMai"));

                    b.Property<bool?>("ApDungVoiDonHang")
                        .HasColumnType("bit");

                    b.Property<string>("MaKM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaKhuyenMai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MucGiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKhuyenMai");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("DATN_WebDT.Models.NguyenLieu", b =>
                {
                    b.Property<int?>("IdNguyenLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdNguyenLieu"));

                    b.Property<string>("DonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhaCungCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenNguyenLieu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNguyenLieu");

                    b.ToTable("NguyenLieus");
                });

            modelBuilder.Entity("DATN_WebDT.Models.NhanVien", b =>
                {
                    b.Property<int>("IdNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNhanVien"));

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNhanVien");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("DATN_WebDT.Models.NhomDoUong", b =>
                {
                    b.Property<int>("IdNhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNhom"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThaiNhom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNhom");

                    b.ToTable("NhomDoUongs");
                });

            modelBuilder.Entity("DATN_WebDT.Models.SanPham", b =>
                {
                    b.Property<int>("IdSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSanPham"));

                    b.Property<decimal>("GiaGoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GiaGocVAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GiaYeuThich")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdNhomDoUong")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiSP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSanPham");

                    b.HasIndex("IdNhomDoUong");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("DATN_WebDT.Models.SanPhamChiTiet", b =>
                {
                    b.Property<int>("IdSanPhamChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSanPhamChiTiet"));

                    b.Property<string>("DoNgot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiaModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdSanPham")
                        .HasColumnType("int");

                    b.Property<string>("SizeCoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBienThe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSanPhamChiTiet");

                    b.HasIndex("IdSanPham");

                    b.ToTable("SanPhamCTs");
                });

            modelBuilder.Entity("DATN_WebDT.Models.SanPhamChiTiet_Topping", b =>
                {
                    b.Property<int>("IdSanPhamChiTiet")
                        .HasColumnType("int");

                    b.Property<int>("IdTopping")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GiaThem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdSanPhamChiTiet", "IdTopping");

                    b.HasIndex("IdTopping");

                    b.ToTable("SanPhamChiTiet_Toppings");
                });

            modelBuilder.Entity("DATN_WebDT.Models.TaiKhoan", b =>
                {
                    b.Property<int>("IdTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTaiKhoan"));

                    b.Property<int?>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTaiKhoan");

                    b.HasIndex("IdKhachHang")
                        .IsUnique()
                        .HasFilter("[IdKhachHang] IS NOT NULL");

                    b.HasIndex("IdNhanVien")
                        .IsUnique()
                        .HasFilter("[IdNhanVien] IS NOT NULL");

                    b.ToTable("taiKhoans");
                });

            modelBuilder.Entity("DATN_WebDT.Models.ThanhToan", b =>
                {
                    b.Property<int>("IdThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThanhToan"));

                    b.Property<int>("HinhThuc")
                        .HasColumnType("int");

                    b.Property<int>("IdHoaDon")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdThanhToan");

                    b.HasIndex("IdHoaDon");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("DATN_WebDT.Models.TonKho", b =>
                {
                    b.Property<int?>("IdTonKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdTonKho"));

                    b.Property<int?>("IdKho")
                        .HasColumnType("int");

                    b.Property<int?>("IdNguyenLieu")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdTonKho");

                    b.HasIndex("IdKho");

                    b.HasIndex("IdNguyenLieu");

                    b.ToTable("TonKhos");
                });

            modelBuilder.Entity("DATN_WebDT.Models.Topping", b =>
                {
                    b.Property<int?>("IdTopping")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdTopping"));

                    b.Property<decimal?>("GiaTopping")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenTopping")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTopping");

                    b.ToTable("Toppings");
                });

            modelBuilder.Entity("DATN_WebDT.Models.AnhSanPham", b =>
                {
                    b.HasOne("DATN_WebDT.Models.SanPhamChiTiet", "SanPhamCT")
                        .WithMany()
                        .HasForeignKey("IdModelSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_WebDT.Models.SanPhamChiTiet", null)
                        .WithMany("AnhSanPhams")
                        .HasForeignKey("SanPhamChiTietIdSanPhamChiTiet");

                    b.HasOne("DATN_WebDT.Models.SanPham", null)
                        .WithMany("AnhSanPhams")
                        .HasForeignKey("SanPhamIdSanPham");

                    b.Navigation("SanPhamCT");
                });

            modelBuilder.Entity("DATN_WebDT.Models.ChiTietCongThuc", b =>
                {
                    b.HasOne("DATN_WebDT.Models.NguyenLieu", "NguyenLieu")
                        .WithMany("CTCTs")
                        .HasForeignKey("IdNguyenLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_WebDT.Models.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("CTCTs")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguyenLieu");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("DATN_WebDT.Models.DiaChi", b =>
                {
                    b.HasOne("DATN_WebDT.Models.KhachHang", "KhachHang")
                        .WithMany("Diachi")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DATN_WebDT.Models.DonHang", b =>
                {
                    b.HasOne("DATN_WebDT.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("HoaDonIdHoaDon");

                    b.HasOne("DATN_WebDT.Models.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DATN_WebDT.Models.NhanVien", "NhanVien")
                        .WithMany("DonHangs")
                        .HasForeignKey("NhanVienIdNhanVien");

                    b.Navigation("HoaDon");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DATN_WebDT.Models.DonHangChiTiet", b =>
                {
                    b.HasOne("DATN_WebDT.Models.DonHang", "DonHang")
                        .WithMany("DonHangChiTiets")
                        .HasForeignKey("IdDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_WebDT.Models.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("IdKhuyenMai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DATN_WebDT.Models.SanPhamChiTiet", "SanPhamCT")
                        .WithMany()
                        .HasForeignKey("IdModelSanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DATN_WebDT.Models.SanPhamChiTiet", null)
                        .WithMany("DonHangChiTiets")
                        .HasForeignKey("SanPhamChiTietIdSanPhamChiTiet");

                    b.Navigation("DonHang");

                    b.Navigation("KhuyenMai");

                    b.Navigation("SanPhamCT");
                });

            modelBuilder.Entity("DATN_WebDT.Models.GioHang", b =>
                {
                    b.HasOne("DATN_WebDT.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DATN_WebDT.Models.GioHangChiTiet", b =>
                {
                    b.HasOne("DATN_WebDT.Models.GioHang", "GioHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_WebDT.Models.SanPhamChiTiet", "SanPhamCT")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdModelSanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("SanPhamCT");
                });

            modelBuilder.Entity("DATN_WebDT.Models.HoaDon", b =>
                {
                    b.HasOne("DATN_WebDT.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DATN_WebDT.Models.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("IdKhuyenMai")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DATN_WebDT.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DATN_WebDT.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("DATN_WebDT.Models.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_WebDT.Models.SanPhamChiTiet", "SanPhamCT")
                        .WithMany()
                        .HasForeignKey("IdModelSanPham")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamCT");
                });

            modelBuilder.Entity("DATN_WebDT.Models.SanPham", b =>
                {
                    b.HasOne("DATN_WebDT.Models.NhomDoUong", "NhomDoUong")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdNhomDoUong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhomDoUong");
                });

            modelBuilder.Entity("DATN_WebDT.Models.SanPhamChiTiet", b =>
                {
                    b.HasOne("DATN_WebDT.Models.SanPham", "SanPham")
                        .WithMany("ModelSanPhams")
                        .HasForeignKey("IdSanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DATN_WebDT.Models.SanPhamChiTiet_Topping", b =>
                {
                    b.HasOne("DATN_WebDT.Models.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("SanPhamChiTiet_Toppings")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_WebDT.Models.Topping", "Topping")
                        .WithMany("SanPhamChiTiet_Toppings")
                        .HasForeignKey("IdTopping")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPhamChiTiet");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("DATN_WebDT.Models.TaiKhoan", b =>
                {
                    b.HasOne("DATN_WebDT.Models.KhachHang", "KhachHang")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("DATN_WebDT.Models.TaiKhoan", "IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DATN_WebDT.Models.NhanVien", "NhanVien")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("DATN_WebDT.Models.TaiKhoan", "IdNhanVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DATN_WebDT.Models.ThanhToan", b =>
                {
                    b.HasOne("DATN_WebDT.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("DATN_WebDT.Models.TonKho", b =>
                {
                    b.HasOne("DATN_WebDT.Models.Kho", "Kho")
                        .WithMany("TonKhos")
                        .HasForeignKey("IdKho")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DATN_WebDT.Models.NguyenLieu", "NguyenLieu")
                        .WithMany("TonKhos")
                        .HasForeignKey("IdNguyenLieu")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Kho");

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("DATN_WebDT.Models.DonHang", b =>
                {
                    b.Navigation("DonHangChiTiets");
                });

            modelBuilder.Entity("DATN_WebDT.Models.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("DATN_WebDT.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("DATN_WebDT.Models.KhachHang", b =>
                {
                    b.Navigation("Diachi");

                    b.Navigation("DonHangs");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DATN_WebDT.Models.Kho", b =>
                {
                    b.Navigation("TonKhos");
                });

            modelBuilder.Entity("DATN_WebDT.Models.NguyenLieu", b =>
                {
                    b.Navigation("CTCTs");

                    b.Navigation("TonKhos");
                });

            modelBuilder.Entity("DATN_WebDT.Models.NhanVien", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DATN_WebDT.Models.NhomDoUong", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DATN_WebDT.Models.SanPham", b =>
                {
                    b.Navigation("AnhSanPhams");

                    b.Navigation("ModelSanPhams");
                });

            modelBuilder.Entity("DATN_WebDT.Models.SanPhamChiTiet", b =>
                {
                    b.Navigation("AnhSanPhams");

                    b.Navigation("CTCTs");

                    b.Navigation("DonHangChiTiets");

                    b.Navigation("GioHangChiTiets");

                    b.Navigation("SanPhamChiTiet_Toppings");
                });

            modelBuilder.Entity("DATN_WebDT.Models.Topping", b =>
                {
                    b.Navigation("SanPhamChiTiet_Toppings");
                });
#pragma warning restore 612, 618
        }
    }
}
